"""Generate complete, on-demand Pretendard subsets with fonttools[woff].

Run from any directory: python scripts/subset-fonts.py
The generated fonts/CSS are checked in; normal npm builds need no Python.
"""

from collections import defaultdict
from pathlib import Path

from fontTools import subset
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/assets/fonts/pretendard-source"
OUTPUT = ROOT / "src/assets/fonts/pretendard-subsets"
CSS = ROOT / "src/app/styles/pretendard.css"
WEIGHTS = {"Regular": 400, "Medium": 500, "Bold": 700}


def is_common_hangul(codepoint):
    # KS X 1001's 2,350 syllables; independent of today's posts, including future text.
    try:
        return len(chr(codepoint).encode("euc_kr")) == 2
    except UnicodeEncodeError:
        return False


def groups_for(codepoints):
    groups = defaultdict(set)
    for codepoint in sorted(codepoints):
        if not 0xAC00 <= codepoint <= 0xD7A3:
            name = "base"
        elif is_common_hangul(codepoint):
            name = "hangul-common"
        else:
            name = f"hangul-{(codepoint - 0xAC00) // 1024:02d}"
        groups[name].add(codepoint)
    return groups


def unicode_ranges(codepoints):
    result = []
    start = end = None
    for codepoint in sorted(codepoints):
        if end is not None and codepoint == end + 1:
            end = codepoint
            continue
        if start is not None:
            result.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
        start = end = codepoint
    if start is not None:
        result.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
    return ",".join(result)


def outline(glyphs, name):
    pen = DecomposingRecordingPen(glyphs)
    glyphs[name].draw(pen)
    return pen.value


def rename_subset(font, label, group):
    # The upstream OFL reserves "Pretendard"; give modified font files a new name.
    names = {
        1: "Blog Sans", 2: label, 3: f"BlogSans-{label}-{group}",
        4: f"Blog Sans {label}", 6: f"BlogSans-{label}-{group}",
        16: "Blog Sans", 17: label, 18: f"Blog Sans {label}",
        21: "Blog Sans", 22: label,
    }
    for record in font["name"].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    rules = ["/* Generated by scripts/subset-fonts.py; do not edit by hand. */"]
    expected_files = set()
    for label, weight in WEIGHTS.items():
        source = SOURCE / f"Pretendard-{label}.woff2"
        original = TTFont(source)
        cmap = original.getBestCmap()
        original_glyphs = original.getGlyphSet()
        covered = set()
        initial_bytes = 0
        for group, codepoints in groups_for(cmap).items():
            font = TTFont(source)
            options = subset.Options()
            options.layout_features = ["*"]
            options.name_IDs = ["*"]  # Preserve copyright and license metadata.
            options.name_languages = ["*"]
            options.glyph_names = True
            options.notdef_outline = True
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=codepoints)
            subsetter.subset(font)
            rename_subset(font, label, group)
            filename = f"BlogSans-{label}-{group}.woff2"
            target = OUTPUT / filename
            font.flavor = "woff2"
            font.save(target)
            expected_files.add(filename)

            # Validate the encoded output, not just the in-memory subset.
            saved = TTFont(target)
            saved_cmap = saved.getBestCmap()
            glyphs = saved.getGlyphSet()
            assert codepoints <= saved_cmap.keys(), f"Missing characters: {filename}"
            for codepoint in codepoints:
                old_name, new_name = cmap[codepoint], saved_cmap[codepoint]
                assert original_glyphs[old_name].width == glyphs[new_name].width
                assert outline(original_glyphs, old_name) == outline(glyphs, new_name)
            assert not covered & codepoints, f"Overlapping unicode ranges: {filename}"
            covered.update(codepoints)
            if group in ("base", "hangul-common"):
                initial_bytes += target.stat().st_size
            rules.append(
                '@font-face {\n  font-family: "Blog Sans";\n'
                f'  src: url("../../assets/fonts/pretendard-subsets/{filename}") format("woff2");\n'
                f"  font-weight: {weight};\n  font-style: normal;\n  font-display: swap;\n"
                f"  unicode-range: {unicode_ranges(codepoints)};\n}}"
            )
            saved.close()
            font.close()
        assert covered == cmap.keys(), f"Incomplete coverage for {label}"
        print(f"{label}: all {len(covered):,} characters and outlines verified; "
              f"base + common Hangul {initial_bytes:,} / {source.stat().st_size:,} bytes")
        original.close()

    # Retain the Arial metric overrides previously generated by next/font/local.
    rules.append('''@font-face {
  font-family: "Pretendard Fallback";
  src: local("Arial");
  ascent-override: 93.76%;
  descent-override: 23.75%;
  line-gap-override: 0%;
  size-adjust: 101.55%;
}

:root {
  --font-pretendard: "Blog Sans", "Pretendard Fallback";
}''')
    CSS.write_text("\n\n".join(rules) + "\n")
    for stale in OUTPUT.glob("*.woff2"):
        if stale.name not in expected_files:
            stale.unlink()


if __name__ == "__main__":
    main()
